CREATE DATABASE openpay_auth;
CREATE DATABASE openpay_merchant;
CREATE DATABASE openpay_payment;
CREATE DATABASE openpay_router;
CREATE DATABASE openpay_webhook;
CREATE DATABASE openpay_ledger;
CREATE DATABASE openpay_settlement;
CREATE DATABASE openpay_notification;
CREATE DATABASE openpay_fraud;
