#!/bin/sh
# Creates the demo merchant and its credentials, once, so that nobody has to.
#
# The problem this solves is small and completely blocking: the shop needs two API keys and the
# dashboard needs a login, all four of which only exist after the platform is running — so the
# honest instruction used to be "start the stack, run a script, copy two values into a file, restart
# the shop". That is four steps too many for someone who was sent a link.
#
# Why a separate container rather than the shop provisioning itself: creating a merchant and minting
# API keys requires the admin token, which is the credential that can do anything on this platform.
# The whole point of demo-storefront is that a merchant integration holds nothing but its own key.
# Letting it hold the admin token to bootstrap itself would make the one thing it exists to
# demonstrate untrue. So the admin token lives here, in a container that runs for two seconds and
# exits, and the shop reads only the credentials it is entitled to.
#
# POSIX sh, curl and sed — no jq, no python. This runs in curlimages/curl, and adding a package
# manager step to a startup path is a way to make the demo depend on a network mirror being up.
set -eu

CREDENTIALS=/demo/demo.properties

# Idempotent, and this is the important part rather than a nicety. Compose re-runs this on every
# `up`, and a provisioner that minted a fresh merchant each time would leave the dashboard login
# printed on the shop's front page pointing at an account with none of the payments in it.
if [ -f "$CREDENTIALS" ]; then
    echo "Demo credentials already provisioned; leaving them alone."
    exit 0
fi

# Prove the file can be written *before* creating anything, not after.
#
# Learned the hard way: this script onboarded a merchant, minted two keys, and only then discovered
# the volume was not writable — so every retry left another orphan merchant behind in the database
# with credentials nobody would ever hold. An init container that fails should leave no trace, and
# the only way to get that here is to check the last step first.
if ! touch "$CREDENTIALS" 2>/dev/null; then
    echo "Cannot write $CREDENTIALS. The volume is not writable by this container, and nothing" >&2
    echo "has been created — fix the mount rather than the database." >&2
    exit 1
fi
rm -f "$CREDENTIALS"

GATEWAY="${GATEWAY_BASE_URL:-http://gateway-service:8080}"
AUTH="${AUTH_SERVICE_BASE_URL:-http://auth-service:8081}"
ADMIN="X-Admin-Token: ${OPENPAY_ADMIN_TOKEN:?the provisioner needs the admin token}"
JSON="Content-Type: application/json"

# Pulls one string field out of a JSON object. Sufficient here because every response this script
# reads is a flat object whose values are strings, and it keeps the image dependency-free.
field() {
    sed -n "s/.*\"$1\":\"\([^\"]*\)\".*/\1/p"
}

# Unique per provisioning run, so a `down -v` and a fresh start do not collide with the previous
# merchant code, which is unique-constrained.
SUFFIX=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 8)
PASSWORD="demo-$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 12)"
EMAIL="owner@demo-$SUFFIX.openpay.test"

echo "Onboarding merchant demo-$SUFFIX"
MERCHANT_ID=$(curl -sS -X POST "$GATEWAY/api/v1/merchants" -H "$ADMIN" -H "$JSON" \
    -d "{\"merchantCode\":\"demo-$SUFFIX\",\"legalName\":\"Kettle & Co\",\"webhookUrl\":null,\"defaultCurrency\":\"INR\"}" \
    | field id)

if [ -z "$MERCHANT_ID" ]; then
    echo "Could not create the demo merchant; leaving credentials unwritten so this retries." >&2
    exit 1
fi

# The secret key. Stays on the shop's server, takes the payment.
API_KEY=$(curl -sS -X POST "$AUTH/api/v1/api-keys" -H "$ADMIN" -H "$JSON" \
    -d "{\"merchantId\":\"$MERCHANT_ID\",\"name\":\"storefront-server\",\"scope\":\"payments:write\",\"expiresAt\":null}" \
    | field apiKey)

# The publishable key. Goes into the checkout page, where anyone can read it, and can do nothing
# but turn a card into a token.
PUBLISHABLE_KEY=$(curl -sS -X POST "$AUTH/api/v1/api-keys" -H "$ADMIN" -H "$JSON" \
    -d "{\"merchantId\":\"$MERCHANT_ID\",\"name\":\"storefront-checkout\",\"scope\":\"tokens:create\",\"expiresAt\":null}" \
    | field apiKey)

curl -sS -o /dev/null -X POST "$AUTH/api/v1/users" -H "$ADMIN" -H "$JSON" \
    -d "{\"merchantId\":\"$MERCHANT_ID\",\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\",\"role\":\"MERCHANT_ADMIN\"}"

if [ -z "$API_KEY" ] || [ -z "$PUBLISHABLE_KEY" ]; then
    echo "A credential came back empty; not writing a half-provisioned file." >&2
    exit 1
fi

# Written last and in one go. A partial file would be read by the shop as a complete one — Spring
# does not know the difference — and the failure would surface as a checkout that 401s rather than
# as a provisioning error anyone could find.
cat > "$CREDENTIALS" <<PROPERTIES
# Generated by platform/docker/demo/provision.sh. Delete this file to provision a fresh merchant.
storefront.api-key=$API_KEY
storefront.publishable-key=$PUBLISHABLE_KEY
storefront.merchant-id=$MERCHANT_ID
# Shown on the shop's own page, because a demo whose dashboard nobody can log into is half a demo.
# These are deliberately displayed: this merchant exists only for the demo and owns nothing real.
storefront.dashboard-email=$EMAIL
storefront.dashboard-password=$PASSWORD
PROPERTIES

echo "Provisioned merchant $MERCHANT_ID"
echo "Dashboard login: $EMAIL / $PASSWORD"
