#!/usr/bin/env bash
# Brings the platform up inside a Codespace and prints where to look.
#
# Everything here exists because a Codespace is not a laptop in two specific ways: each forwarded
# port gets its own hostname, and the credentials the compose files require have to come from
# somewhere without a human typing them. Both are handled below; nothing else about the stack
# changes, and the compose files this calls are the same ones a real deployment uses.
set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_DIR=platform/docker
ENV_FILE="$COMPOSE_DIR/.env"

COMPOSE=(docker compose
    -f "$COMPOSE_DIR/docker-compose.yml"
    -f "$COMPOSE_DIR/docker-compose.apps.yml"
    -f "$COMPOSE_DIR/docker-compose.codespaces.yml"
    --profile shop)

# Deterministic from the Codespace name, and available long before the ports are actually
# forwarded — which matters, because the dashboard image bakes these in at build time and the
# build starts well before anything listens.
if [ -n "${CODESPACE_NAME:-}" ]; then
    DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
    PUBLIC_URL="https://${CODESPACE_NAME}-8000.${DOMAIN}"
    DASHBOARD_URL="https://${CODESPACE_NAME}-5173.${DOMAIN}"
else
    # Run outside a Codespace — on a laptop, or in a plain devcontainer — this still works, and
    # falls back to the addresses that are true there.
    PUBLIC_URL="http://localhost:8000"
    DASHBOARD_URL="http://localhost:5173"
fi

print_urls() {
    cat <<BANNER

  ─────────────────────────────────────────────────────────────────────
   OpenPay is running.

   Shop        ${PUBLIC_URL}
               A card number, and a payment that reaches captured on its
               own. The dashboard login is printed on this page.

   Dashboard   ${DASHBOARD_URL}
               The same payment from the merchant's side.
  ─────────────────────────────────────────────────────────────────────

BANNER
}

if [ "${1:-}" = "--print-only" ]; then
    print_urls
    exit 0
fi

# Written once and then left alone: demo-provisioner mints the merchant against whatever the admin
# token was on first boot, so regenerating these on a later start would leave the dashboard login
# pointing at an account that no longer authenticates.
if [ ! -f "$ENV_FILE" ]; then
    echo "Generating credentials in $ENV_FILE"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by .devcontainer/start-demo.sh. Not committed — .env is in .gitignore.
#
# Random per Codespace rather than the published development defaults, because a forwarded port
# can be made public in one click and the admin token alone can mint API keys.
OPENPAY_ADMIN_TOKEN=$(openssl rand -base64 32)
OPENPAY_OPS_TOKEN=$(openssl rand -base64 32)
OPENPAY_INTERNAL_TOKEN=$(openssl rand -base64 32)
OPENPAY_JWT_SECRET=$(openssl rand -base64 48)
MOCK_BANK_A_SECRET=$(openssl rand -base64 24)
MOCK_BANK_B_SECRET=$(openssl rand -base64 24)

# The dashboard is a genuinely separate origin and needs the CORS answer. The shop does not: the
# edge proxy serves it and the API from OPENPAY_PUBLIC_URL, so tokenisation is same-origin.
OPENPAY_PUBLIC_URL=${PUBLIC_URL}
OPENPAY_DASHBOARD_ORIGINS=${DASHBOARD_URL}
STOREFRONT_GATEWAY_PUBLIC_URL=${PUBLIC_URL}
EOF
fi

echo "Building and starting. First run compiles the Maven reactor once — expect ~10 minutes."
"${COMPOSE[@]}" up -d --build

# Private forwarded ports sit behind a GitHub login, which a page can pass (the browser is already
# authenticated) but a cross-origin fetch cannot — so the dashboard's calls to the API would be
# answered by a login redirect instead of by the gateway. Public visibility on 8000 is what makes
# the dashboard work; the shop is same-origin and works either way.
#
# Best-effort: the in-Codespace token often lacks the scope for this, and a demo that dies here
# would be worse than one that prints the click.
if [ -n "${CODESPACE_NAME:-}" ]; then
    if ! gh codespace ports visibility 8000:public -c "$CODESPACE_NAME" >/dev/null 2>&1; then
        cat <<'NOTE'

  Note: could not set port 8000 to public automatically.
  The shop works as-is. For the dashboard, open the Ports tab, right-click
  port 8000 -> Port Visibility -> Public.

NOTE
    fi
fi

print_urls
