#!/usr/bin/env bash
# The one command the README promises, made true on a fresh clone.
#
# docker-compose.apps.yml requires five secrets and refuses to start without them — deliberately,
# because an unset admin token meaning "no auth" is how demo credentials end up on the internet.
# That fail-closed design is right and stays. What was missing is the other half: something that
# supplies real values on a machine where no deployment decision has been made yet.
#
# So this generates them once into platform/docker/.env (gitignored, 0600) and starts the stack.
# Every value is random per clone, which means the published development tokens in docs/ are not
# what a reader ends up running, and nothing here is a secret anyone else already knows.
#
# For a real deployment follow docs/DEPLOY.md instead. It does the same thing deliberately, with
# the rest of the steps this skips: TLS, a firewall, and a host that is not a laptop.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=platform/docker/.env

if [ ! -f "$ENV_FILE" ]; then
    echo "Generating credentials in $ENV_FILE"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/demo.sh. Gitignored, and regenerating it after the demo merchant has been
# provisioned would leave the dashboard login pointing at an account that no longer authenticates
# — delete the volumes too if you want a genuinely clean start:
#   docker compose -f platform/docker/docker-compose.yml -f platform/docker/docker-compose.apps.yml --profile shop down -v
OPENPAY_ADMIN_TOKEN=$(openssl rand -base64 32)
OPENPAY_OPS_TOKEN=$(openssl rand -base64 32)
OPENPAY_INTERNAL_TOKEN=$(openssl rand -base64 32)
OPENPAY_JWT_SECRET=$(openssl rand -base64 48)
MOCK_BANK_A_SECRET=$(openssl rand -base64 24)
MOCK_BANK_B_SECRET=$(openssl rand -base64 24)

# The dashboard is served from a different origin than the API and needs the CORS answer. This is
# where it is published locally; docs/DEPLOY.md sets it to a real hostname.
OPENPAY_DASHBOARD_ORIGINS=http://localhost:5173
EOF
fi

docker compose \
    -f platform/docker/docker-compose.yml \
    -f platform/docker/docker-compose.apps.yml \
    --profile shop up -d

cat <<'BANNER'

  Shop        http://localhost:8090   the login for the dashboard is on this page
  Dashboard   http://localhost:5173

BANNER
